### ISSUE TITLE
Credit me please.

### ISSUE THREAD

**Issue by joseywoermann** [byZeroOfficial/ZeroBot#15]
According to the GPL v3 license which I use in [navnløs](https://github.com/joseywoermann/navnlos), you have to give credit [here](https://github.com/byZeroOfficial/ZeroBot/blob/b31e9a9335db901e50e53f46edd9dbd7218e28d7/ZeroBot/bot.py#L415) in your code, because you "took" that feature from my code.

Thank you.

**Comment by byZeroOfficial** [comment]
Hey,
I will do credit in the next 2.0 Update, it would be stupid, if I make a new release cause of this.
Is 1 week or 2 weeks okay with you?

**Comment by joseywoermann** [comment]
> Is 1 week or 2 weeks okay with you?

That's fine.

**Comment by byZeroOfficial** [comment]
Okay :)
