### ISSUE TITLE
Support Slash Commands

### ISSUE THREAD

**Issue by joseywoermann** [byZeroOfficial/ZeroBot#20]
**Is your feature request related to a problem? Please describe.**
Currently, you almost always have to look at the help-menu or remember the syntax. If you get the syntax even slightly wrong, nothing works and you don't get an error message which explains what happened.

**Describe the solution you'd like**
Add Slash Commands. These make it obvious how to use the command (like seen below), and prevent errors, because they can't be send if you get the syntax wrong.
![image](https://user-images.githubusercontent.com/67111271/118362933-3b51c780-b592-11eb-9dff-ad2ccff11946.png)

**Describe alternatives you've considered**
Add proper Error-Messages, but these don't make the syntax clear.

**Additional context**
Slash Commands are currently **not** natively supported by the discord.py-library, but you use them easily with [this library](https://pypi.org/project/discord-py-slash-command/).

**Comment by byZeroOfficial** [comment]
Hello!
I will definitely check it out in the next few days. Thanks for your idea!

**Comment by byZeroOfficial** [comment]
Hey, i implemented it.
There's just one question left:

How did you make those error messages?

**Comment by byZeroOfficial** [comment]
@joseywoermann

**Comment by joseywoermann** [comment]
> Hey, i implemented it.
> There's just one question left:
> 
> How did you make those error messages?


You should try and implement this yourself to actually learn something without just copy-pasting. I also recommend reading the [docs](https://docs.python.org/3/tutorial/errors.html#handling-exceptions).

**Comment by byZeroOfficial** [comment]
Okay :D
