### ISSUE TITLE
Stop changing sites automatically

### ISSUE THREAD

**Issue by therealmistericraft** [byZeroOfficial/ZeroBot#24]
When you look at the plan, the site changes after a few seconds. It is very bad to look at a lesson if it is not there anymore after a few seconds.

**Describe the solution you'd like**
The sites should stay until you manually change it

**Describe alternatives you've considered**
You could add a switch in the app settings, like you suggested.

**Comment by byZeroOfficial** [comment]
Hey Mistericraft,

I didn't know yet that the ZeroBot had changing sites. And an app? Isn't the ZeroBot is a Discord Bot??? 😂

Could it be that you mixed up the repositories? I think you're looking for the Vertretungsplan-App.

You can find the repository for the app [here](https://GitHub.com/KGH-Vertretungsplan-App/App)!

Greetings
byZero

**Comment by joseywoermann** [comment]
> When you look at the plan, the site changes after a few seconds. It is very bad to look at a lesson if it is not there anymore after a few seconds.
> 
> **Describe the solution you'd like**
> The sites should stay until you manually change it
> 
> **Describe alternatives you've considered**
> You could add a switch in the app settings, like you suggested.
> 

What in the world are you even talking about?

**Comment by therealmistericraft** [comment]
Oops wrong ***@***.*** can you transfer the issue?On 16 Jun 2021 20:10, Josey Wörmann ***@***.***> wrote:

When you look at the plan, the site changes after a few seconds. It is very bad to look at a lesson if it is not there anymore after a few seconds.
Describe the solution you'd like
The sites should stay until you manually change it
Describe alternatives you've considered
You could add a switch in the app settings, like you suggested.

What in the world are you even talking about?

**Comment by joseywoermann** [comment]
> Oops wrong ***@***.*** can you transfer the issue?On 16 Jun 2021 20:10, Josey Wörmann ***@***.***> wrote:
> 
> When you look at the plan, the site changes after a few seconds. It is very bad to look at a lesson if it is not there anymore after a few seconds.
> Describe the solution you'd like
> The sites should stay until you manually change it
> Describe alternatives you've considered
> You could add a switch in the app settings, like you suggested.
> 
> What in the world are you even talking about?
> 
> —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

This confuses me even more

**Comment by byZeroOfficial** [comment]
Yep, me too
![what in the hell](https://user-images.githubusercontent.com/76685126/122274064-707b6d80-cee2-11eb-9691-42d7f4600577.png)

**Comment by byZeroOfficial** [comment]
what now?

**Comment by joseywoermann** [comment]
> 
> 
> what now?

idk, ask @therealmistericraft

**Comment by byZeroOfficial** [comment]
@therealmistericraft what now?

**Comment by therealmistericraft** [comment]
I think this case is closed, right?

**Comment by joseywoermann** [comment]
> 
> 
> I think this case is closed, right?

![image](https://user-images.githubusercontent.com/67111271/123525634-7c311600-d6d2-11eb-9543-4e22b9be9d36.png)

**Comment by byZeroOfficial** [comment]
If you would reply on this: https://github.com/KGH-Vertretungsplan-App/App/issues/7

**Comment by byZeroOfficial** [comment]
Wow
Now you did

**Comment by byZeroOfficial** [comment]
![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/whatsapp/273/face-with-rolling-eyes_1f644.png)
