### ISSUE TITLE
Giveaway-Bot Replacement

### ISSUE THREAD

**Issue by zerobot-issues** [byZeroOfficial/ZeroBot#6]
Add a giveaway-feature to replace GiveawayBot (Issue created by @joseywoermann)

**Comment by joseywoermann** [comment]
Great idea, I wonder who has such creative ideas.

**Comment by byZeroOfficial** [comment]
xD

**Comment by byZeroOfficial** [comment]
I'm thinking about your _idea_, but it's probably hard to implement. But I'll put it on my _"to do"_ list.

**Comment by joseywoermann** [comment]
@byZeroOfficial You can close this issue.

**Comment by byZeroOfficial** [comment]
Yep, so I did it ;D
