### ISSUE TITLE
optimize Help-Command

### ISSUE THREAD

**Issue by zerobot-issues** [byZeroOfficial/ZeroBot#9]
Add MarkDown-Files into the GitHub-Repository, so you can make a list of commands in groups. For example: Group A = General, Group B = Fun, Group C = Mod (Issue created by Discord-user `byZero#4840`)

**Comment by therealmistericraft** [comment]
I recommend using the GitHub wiki instead.

**Comment by byZeroOfficial** [comment]
thats right, my head is hurting now cause I was putting it on my desk to hard :)

**Comment by byZeroOfficial** [comment]
hey :) @therealmistericraft i optimized the _help command, how about that?
